import { Router } from 'express';
import { asyncHandler as h } from '../middleware/asyncHandler.js';
import { rateLimit } from '../middleware/rateLimit.js';
import * as history from '../services/historyService.js';
import * as media from '../services/mediaService.js';
import * as push from '../services/pushService.js';
import * as xp from '../services/xpService.js';
import { scrape } from '../services/designScrapeService.js';
const r = Router();
r.get('/history', h((req, res) => res.json(history.list(req.query))));
r.post('/history/:id/undo', h((req, res) => res.json(history.undo(req.params.id, !!req.body?.force, req.user))));
r.post('/design/scrape', rateLimit(10, 60000), h(async (req, res) => res.json(await scrape(String(req.body?.url || '')))));
r.post('/media/snapshot', rateLimit(10, 60000), h(async (_q, res) => res.json(await media.snapshot())));
r.get('/media/snapshots', h((_q, res) => res.json(media.listSnapshots())));
r.post('/media/clips/:id/archive', rateLimit(6, 60000), h(async (req, res) => res.json(await media.archiveClip(req.params.id))));
r.delete('/media/archive/:id', h((req, res) => res.json(media.removeArchived(req.params.id))));
r.post('/notifications/send', rateLimit(10, 60000), h(async (req, res) => res.json(await push.announce(req.body || {}))));
r.get('/notifications/stats', h((_q, res) => res.json(push.stats())));
r.delete('/xp', h((_q, res) => res.json(xp.reset())));
export default r;
