import { Router } from 'express';
import { getBot, putBot, chat, send, doSubscribe, subscriptions } from '../controllers/botController.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
const r = Router();
r.get('/bot', asyncHandler(getBot));
r.put('/bot', asyncHandler(putBot));
r.get('/bot/chat', asyncHandler(chat));
r.post('/bot/send', asyncHandler(send));
r.post('/bot/subscribe', asyncHandler(doSubscribe));
r.get('/bot/subscriptions', asyncHandler(subscriptions));
export default r;
