import { Router } from 'express';
import * as c from '../controllers/discordBotController.js';
import { asyncHandler as h } from '../middleware/asyncHandler.js';
const r = Router();
r.get('/discord/status', h(c.status));
r.get('/discord/info', h(c.info));
r.get('/discord/settings', h(c.getSettings));
r.put('/discord/settings', h(c.putSettings));
r.post('/discord/send', h(c.send));
r.post('/discord/ticket-panel', h(c.panel));
r.post('/discord/moderate', h(c.moderate));
r.post('/discord/announce-test', h(c.testAnnounce));
r.get('/discord/logs', h(c.logs));
r.delete('/discord/logs', h(c.clearLogs));
r.get('/discord/tickets', h(c.tickets));
r.post('/discord/tickets/:id/close', h(c.closeTicket));
export default r;
