import { Router } from 'express';
import { requireAdmin } from '../middleware/auth.js';
import publicRoutes from './publicRoutes.js';
import authRoutes from './authRoutes.js';
import configRoutes from './configRoutes.js';
import backupRoutes from './backupRoutes.js';
import versionRoutes from './versionRoutes.js';
import assetRoutes from './assetRoutes.js';
import kickRoutes from './kickRoutes.js';
import maintenanceRoutes from './maintenanceRoutes.js';
import modsRoutes from './modsRoutes.js';
import sectionsRoutes from './sectionsRoutes.js';
import commandsRoutes from './commandsRoutes.js';
import kickAuthAdmin, { publicKickAuth } from './kickAuthRoutes.js';
import botRoutes from './botRoutes.js';
import webhookRoutes from './webhookRoutes.js';
import trackRoutes from './trackRoutes.js';
import securityRoutes from './securityRoutes.js';
import discordBotRoutes from './discordBotRoutes.js';
import staffRoutes from './staffRoutes.js';
import communityRoutes from './communityRoutes.js';
import adminExtraRoutes from './adminExtraRoutes.js';
const api = Router();
api.use(publicRoutes);
api.use(trackRoutes);
api.use(communityRoutes);
api.use(publicKickAuth);
api.use(webhookRoutes);
api.use('/admin', authRoutes);
const admin = Router();
admin.use(requireAdmin);
[configRoutes, backupRoutes, versionRoutes, assetRoutes, kickRoutes, maintenanceRoutes, modsRoutes, sectionsRoutes, commandsRoutes, kickAuthAdmin, botRoutes, securityRoutes, discordBotRoutes, staffRoutes, adminExtraRoutes].forEach(r => admin.use(r));
api.use('/admin', admin);
export default api;
