import { Router } from 'express';
import { info, authStatus, authDisconnect, connectUrl, loginUrl, callback, guardianUrl } from '../controllers/kickAuthController.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { rateLimit } from '../middleware/rateLimit.js';
export const publicKickAuth = Router();
publicKickAuth.get('/kick/oauth/callback', asyncHandler(callback));
publicKickAuth.get('/kick/login-url', rateLimit(20, 60000), asyncHandler(loginUrl));
publicKickAuth.get('/kick/guardian-url', rateLimit(20, 60000), asyncHandler(guardianUrl));
const admin = Router();
admin.get('/kick/info', asyncHandler(info));
admin.get('/kick/auth/status', asyncHandler(authStatus));
admin.get('/kick/auth/url', asyncHandler(connectUrl));
admin.post('/kick/auth/disconnect', asyncHandler(authDisconnect));
export default admin;
