import { Router } from 'express';
import { sync, liveStatus, channelInfo, selectChannel } from '../controllers/kickController.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { rateLimit } from '../middleware/rateLimit.js';
const r = Router();
r.post('/kick/sync', rateLimit(10, 60000), asyncHandler(sync));
r.get('/kick/live', asyncHandler(liveStatus));
r.get('/kick/channel', asyncHandler(channelInfo));
r.post('/kick/channel', asyncHandler(selectChannel));
export default r;
