import { Router } from 'express';
import { list, approve, hide, override, remove, settings } from '../controllers/modsController.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
const r = Router();
r.get('/mods', asyncHandler(list));
r.put('/mods/settings', asyncHandler(settings));
r.put('/mods/:id/approve', asyncHandler(approve));
r.put('/mods/:id/hide', asyncHandler(hide));
r.put('/mods/:id/override', asyncHandler(override));
r.delete('/mods/:id', asyncHandler(remove));
export default r;
