import Database from 'better-sqlite3';
import fs from 'fs';
import path from 'path';
import { env } from '../config/env.js';
import { applySchema } from './schema.js';
export const DATA_DIR = path.resolve(env.dataDir);
export const UPLOAD_DIR = path.join(DATA_DIR, 'uploads');
fs.mkdirSync(UPLOAD_DIR, { recursive: true });
export const db = new Database(path.join(DATA_DIR, 'site.db'));
applySchema(db);
